﻿services:
  back:
    image: kitchen_delights
    build: .
    container_name: kitchen_delights
    ports:
      - "5050:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
