USE [KitchenDelights]
GO

INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Argentina', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Châu Úc', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('New Zealand', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Áo', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Bangladesh', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Bỉ', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Brazil', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Canada', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('ChiLê', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Trung Quốc', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Campuchia', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Colombia', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Cuba', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Đan Mạch', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Ai Cập', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Phần Lan', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Pháp', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Đức', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Greenland', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Hồng Kông', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Hungary', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Iceland', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Ấn Độ', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Indonesia', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Ý', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Nhật Bản', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Lào', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Malaysia', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Mexico', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Hà Lan', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('New Zealand', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Philippines', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Nga', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Singapore', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Thụy Lan', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Thổ Nhĩ Kỳ', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Ukraine', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Anh', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Mỹ', 1)
INSERT INTO [dbo].[countries]([country_name], [country_status])VALUES('Việt Nam', 1)
GO


